import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.By;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

class fnenterpersonaldetailsonprescreeningpageprospect_copy3 {

	public static void fnenterpersonaldetailsonprescreeningpageprospect_copy3() {
		tg.wait("ele_FirstNameField", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_FirstNameField", 1);
		tg.wait("ele_FirstNameEditText", ComparisonType.IS_VISIBLE);
		tg.click("ele_FirstNameEditText", 1);
		tg.wait("ele_FirstNameEditText", ComparisonType.IS_VISIBLE);
		tg.type("ele_FirstNameEditText", "LoopBack");
		tg.wait("ele_LastNameField", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_LastNameField", 1);
		tg.wait("ele_LastNameEditText", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_LastNameEditText", 1);
		tg.wait("ele_LastNameEditText", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_LastNameEditText", "Test");
		tg.wait("ele_DOB", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_DOB", 1);
		tg.wait("ele_DOBeditText", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_DOBeditText", 1);
		tg.wait("ele_DOBeditText", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_DOBeditText", "07251999");
		tg.wait("ele_FourDigitsSSN", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_FourDigitsSSN", 1);
		tg.wait("ele_EditFourDigitsSSN", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_EditFourDigitsSSN", 1);
		tg.wait("ele_EditFourDigitsSSN", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_EditFourDigitsSSN", "0000");
		tg.wait("ele_MobileNumber", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_MobileNumber", 1);
		tg.wait("ele_EditMobileNumber", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_EditMobileNumber", 1);
		tg.wait("ele_EditMobileNumber", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_EditMobileNumber", "4706624138");
		tg.wait("ele_EmailAddresss", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_EmailAddresss", 1);
		tg.wait("ele_EditEmail", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_EditEmail", 1);
		tg.wait("ele_EditEmail", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_EditEmail", "test@gmail.com");
		tg.wait("ele_AccountPIN", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_AccountPIN", 1);
		tg.wait("ele_AccountPIN", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_AccountPIN", "123456");
		tg.wait("ele_AddressField", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_AddressField", 1);
		tg.wait("ele_AddressInput", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_AddressInput", 1);
		tg.wait("ele_AddressInput", ComparisonType.IS_VISIBLE, 10);
		tg.type("ele_AddressInput", "1 Ravinia Dr, Atlanta, GA 30646");
		tg.wait("ele_AddressSuggesstion", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_AddressSuggesstion", 1);
		tg.wait("ele_ESIGNcheckBox", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_ESIGNcheckBox", 1);
		tg.wait("ele_CheckBox2", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_CheckBox2", 1);
		tg.wait("ele_AcceptAndcontinuePreScreenPage", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_AcceptAndcontinuePreScreenPage", 1);
		tg.printLogs("Clicked accept and continue button on pre screen details page");
		tg.wait("ele_ConfirmAddress", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_ConfirmAddress", 1);
		tg.wait("ele_continue026", ComparisonType.IS_VISIBLE);
		tg.click("ele_continue026", 1);
	}
}