import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.By;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

class fncellphoneaddtocart {

	public static void fncellphoneaddtocart() {
		tg.check.isVisible("ele_TmoHomePage");
		tg.testFunction("fnAcceptCookies", new Object[]{});
		tg.check.isVisible("ele_TmoHomePage");
		tg.click("ele_PhonesanddevicesOption", 1);
		tg.check.isVisible("ele_ShopphonesPageTitle");
		tg.check.isVisible("ele_BrandsCheckBoxess");
		tg.click("ele_AppleBrandCheckBox", 1);
		tg.click("ele_iPhone17ProMax", 1);
		tg.wait(20);
		tg.check.isVisible("ele_ProductNameiPhone17ProMax");
		tg.click("ele_iPhone17ProMax256Silver", 1);
		tg.check.isVisible("ele_SamedaydeliveryMethodforProspect");
		tg.click("ele_SamedaydeliveryMethodforProspect", 1);
		tg.scrollToElement("ele_EditLocationBtnforSDD", Direction.DOWN);
		tg.click("ele_EditLocationBtnforSDD", 1);
		// [DISABLED] tg.scrollToElement("ele_ShippingMethod", Direction.DOWN);
		// [DISABLED] tg.click("ele_ShippingMethod", 1);
		// [DISABLED] tg.click("ele_NewCustomer", 1);
		// [DISABLED] tg.wait(5);
		// [DISABLED] tg.check.isVisible("ele_GetANewNumber");
		// [DISABLED] tg.click("ele_GetANewNumber", 1);
		// [DISABLED] tg.wait("ele_skipTradein", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_skipTradein", 1);
		// [DISABLED] tg.wait(5);
		// [DISABLED] tg.click("ele_continueSkipTradeIn", 1);
		// [DISABLED] tg.scrollToElement("ele_DeclineProtectionBTN", Direction.DOWN);
		// [DISABLED] tg.click("ele_DeclineProtectionBTN", 1);
		// [DISABLED] tg.scrollToElement("ele_addtocart", Direction.DOWN);
		// [DISABLED] tg.click("ele_Addtocart1437092149074399", 1);
		// [DISABLED] tg.wait(10);
		// [DISABLED] tg.click("ele_continue891", 1);
		// [DISABLED] tg.click("ele_continue454", 1);
		// [DISABLED] tg.wait(20);
		// [DISABLED] tg.click("ele_continue099", 1);
		// [DISABLED] tg.wait(20);
		// [DISABLED] tg.check.isVisible("ele_cartdatagu622");
		tg.wait(10);
		tg.wait("ele_fieldsdded641", ComparisonType.IS_VISIBLE);
		tg.type("ele_fieldsdded182", "1403 nw sammam");
		tg.wait("ele_Sammamish", ComparisonType.IS_VISIBLE);
		tg.click("ele_Sammamish", 1);
		// [DISABLED] tg.wait("ele_litgwebcom150", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_litgwebcom150", 1);
		// [DISABLED] tg.wait("ele_fieldsdded434", ComparisonType.IS_VISIBLE, 777779999);
		// [DISABLED] tg.wait("ele_fieldsdded510", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_fieldsdded510", 1);
		// [DISABLED] tg.wait("ele_fieldsdded461", ComparisonType.IS_VISIBLE);
		tg.click("ele_fieldsdded461", 1);
		tg.wait("ele_fieldsdded461", ComparisonType.IS_VISIBLE);
		tg.type("ele_fieldsdded461", "9132387465");
		tg.wait("ele_confirmdel753", ComparisonType.IS_VISIBLE);
		tg.click("ele_confirmdel753", 1);
		tg.wait("ele_confirm203", ComparisonType.IS_VISIBLE);
		tg.click("ele_confirm203", 1);
		tg.wait(20);
		tg.click("ele_NewCustomer", 1);
		tg.wait(5);
		tg.click("ele_GetANewNumberBTN", 1);
		tg.wait("ele_skipTradein", ComparisonType.IS_VISIBLE);
		tg.click("ele_skipTradein", 1);
		tg.click("ele_continueSkipTradeIn", 1);
		tg.scrollToElement("ele_DeclineProtectionBTN", Direction.DOWN);
		tg.click("ele_DeclineProtectionBTN", 1);
		tg.click("ele_yesdecline", 1);
		tg.scrollToElement("ele_Addtocart1437092149074399", Direction.DOWN);
		tg.click("ele_AddToCartOption", 1);
		tg.wait(10);
		tg.wait("ele_DecrementLinecountBtn", ComparisonType.IS_VISIBLE);
		tg.click("ele_DecrementLinecountBtn", 2);
		// [DISABLED] tg.wait("ele_svgtgwebcomma906", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_svgtgwebcomma906", 2);
		tg.wait("ele_continue454", ComparisonType.IS_VISIBLE);
		tg.click("ele_continue454", 1);
		tg.wait(10);
		tg.click("ele_SelectyourcreditrangeGood6", 1);
		// [DISABLED] tg.click("ele_selectyour259", 1);
		tg.selectDropdownByValue("ele_selectyour398","GOOD_CREDIT");
		tg.wait(5);
		// [DISABLED] tg.wait("ele_continue461", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_continue461", 1);
		tg.click("ele_ContinueAfterCreditscorechecked", 2);
		// [DISABLED] tg.click("ele_selectyour065", 1);
		// [DISABLED] tg.click("ele_continue891", 1);
		// [DISABLED] tg.wait(20);
		// [DISABLED] tg.click("ele_continue099", 1);
		tg.wait(20);
		// [DISABLED] tg.click("ele_continue099", 1);
		tg.click("ele_PlanpageContinueBtn", 1);
		tg.wait("ele_cartdatagu622", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.testFunction("fnContinutocartforHSISDD", new Object[]{});
		// [DISABLED] tg.click("ele_continueshoppingBtn", 1);
		// [DISABLED] tg.click("ele_homeinternetOption", 1);
		// [DISABLED] tg.wait("ele_universale690", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_universale690", 1);
		// [DISABLED] tg.wait("ele_universale690", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.selectDropdownByValue("ele_selectyour398","GOOD_CREDIT");
		// [DISABLED] tg.wait("ele_continue671", ComparisonType.IS_VISIBLE);
	}
}